#==============================================================
#= Articoli Web Service - Versione Base
#==============================================================

server:
  port: 5051
  
spring:
  application:
    name: ProductWebService
  #==============================================================
  #= DBMS PostgreSql Parameters
  #==============================================================
  dataSource:
    initialization-mode: always
    password: 123_Stella
    platform: postgres
    url: jdbc:postgresql://localhost:5433/alphashop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true